png_homepage:
    path:     /{hash}/w{width}-h{height}-b{background}-t{textColor}
    defaults: 
        _controller: PngWidgetBundle:Default:index 
    requirements:
#       width : '^[0-9]{3}$'
#       height : '^[0-9]{3}$'
#       background : '/([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?\b/'
#       textcolor : '/([a-f]|[A-F]|[0-9]){3}(([a-f]|[A-F]|[0-9]){3})?\b/'

user:
    pattern:  /user/
    defaults: { _controller: PngWidgetBundle:User:index }


user_new:
    pattern:  /user/add/
    defaults: { _controller: PngWidgetBundle:User:new }

user_show:
    pattern:  /user/{id}
    defaults: { _controller: PngWidgetBundle:User:show }
    requirements:
        id:  \d+
        
user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: PngWidgetBundle:User:edit }
    requirements:
        id:  \d+

user_update:
    pattern:  /user/{id}/update
    defaults: { _controller: PngWidgetBundle:User:update }

user_create:
    pattern:  /user/create
    defaults: { _controller: PngWidgetBundle:User:create }

user_delete:
    pattern:  /user/{id}/delete/
    defaults: { _controller: PngWidgetBundle:User:delete }
    requirements:
        id:  \d+